### PR TITLE
Adding option not to fade the previous slide out during transition (#1308)

### PR DESCRIPTION
**Pull request by jsit**
Adding option not to fade the previous slide out during transition; instead, previous slides becomes opacity:0 after next slide has fully faded in.

### CODE REVIEW

**Comment by mattmckenny** [comment]
I agree there should be an option to prevent fading out during the fade transition. The current implementation of the fade transition crossfades the current and target slides and results in a brief flash of the background color during the transition (most noticeable when both are at 0.5 opacity.) This pull request resolves this issue by simply allowing the "new" slide to fade in on top of the "old" one.

**Comment by jeffikus** [comment]
will check this out for 2.7.0

**Comment by scamartist26** [comment]
FYI, if `animation` is set to `slide` this fix causes unexpected behavior.

The conditional lines _should_ look something more like `if (slider.vars.fadeOutDuringTransition == false && slider.vars.animation == 'fade')`. Or maybe this should be a new animation type, removing the need for the additional option.

**Comment by scamartist26** [comment]
Actually, this option should NOT be added to the SLIDE animation at all. So, in this patch, lines 791-793 should be removed.

**Pull request closed without merging**
