### PR TITLE
SASS stylesheets created

### PR DESCRIPTION
**Pull request by floq-design**
Created SASS versions of stylesheets for those that prefer is over LESS

### CODE REVIEW

**Comment by christian-thomas** [comment]
Thanks James — Just what I was looking for :)

**Comment by jeffikus** [comment]
Awesome, will review this soon. Thanks!

**Comment by mikestreety** [comment]
Any luck with this? Would be great to get it folded in - especially as I pull in FS with Bower

**Comment by christian-thomas** [comment]
You could just:

    bower install -S git@github.com:floq-design/FlexSlider#sass

..for the moment at least anyway @mikestreety — Obviously not ideal in the long-term I know.

**Comment by mikestreety** [comment]
Thanks @christian-thomas - forgotten I could do that :+1: 

If I want to update the pull request, do I submit a pull request to @floq-design's repo?

**Comment by jeffikus** [comment]
Updated. Assigned to 2.6.0 milestone.

**Comment by mikestreety** [comment]
I have created a pull request on @floq-design's repo to add default flags - standard practice for sass plugins. Would be good if this could be included.

Thanks!

https://github.com/floq-design/FlexSlider/pull/1

**Comment by floq-design** [comment]
Just pushed latest SASS version with !default flag and sync'd with v2.5

**Comment by jeffikus** [comment]
Ok, in principle I'm happy with this, bumping to the next milestone though - I want to keep 2.6.0 focus on the other issues for now.

**Comment by jostrander** [comment]
Any plans to merge this in in the next release?

**Comment by rockethouse** [comment]
+ 1 This needs to be done.

**Comment by jeffikus** [comment]
Wrapping up 2.6.1 and will hit this next.

**Comment by montalvomiguelo** [comment]
merge?

**Comment by davidstosik** [comment]
This does not seem to be merged into 2.7.0 yet. Anytime this might happen soon?

**Comment by floq-design** [comment]
Updated SASS stylesheets with v2.7.0

**Comment by crabnky** [comment]
Any thoughts when this can be merged?

**Comment by floq-design** [comment]
Updated SASS branch to v2.7.2

**Comment by chrishough** [comment]
Can we please have this merged? Thank you @floq-design for converting this, less is dead

**Pull request closed without merging**
